~Siddhartha
var radius_hem_lead = 7
var height_circular_cone = 49
var radius_circular_cone = (((2/3) * radius_hem_lead^3) / ((1/3) * height_circular_cone))^(1/2)
print("The radius of the circular cone = ", radius_circular_cone)
print(" cm")
