name: C/C++ CI

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: [ubuntu-latest, windows-latest, macos-latest]
    
    steps:
    - uses: actions/checkout@master
    - name: make exec
      run: make exec
